Get income statement and balance sheet data from yahoo finance.

Selected company: JP Morgan Chase & Co. (JPM).

In this notebook, we will retrieve income statement and balance sheet data for JPM from Yahoo Finance over the past 4 years using the `yfinance` library in Python.

In [1]:
# ! pip install yfinance

In [93]:
# import the liobrary and seeting the stock of interest
import yfinance as yf
import pandas as pd

# set the stock ticker symbol 
# Tencent - Listed on the Hong Kong Stock Exchange
Tencent = yf.Ticker('0700.HK')
# JP Morgan Chase - Listed on the New York Stock Exchange (NYSE)
JPM = yf.Ticker('JPM')
# Alibaba
Alibaba_HK = yf.Ticker('9988.HK') # Hong Kong Stock Exchange (HKEX)
# Exxon Mobil - Listed on the NYSE
Exxon = yf.Ticker('XOM')
# Volkswagen
VW_DE = yf.Ticker('VOW3.DE')  # XETRA (Germany).
# Microsoft
Microsoft = yf.Ticker('MSFT')
# Google (Alphabet) 
Google_A = yf.Ticker('GOOGL') # Class A shares (with voting rights)
# Google_C = yf.Ticker('GOOG')  # Class C shares (no voting rights)

ticker_symbol = Google_A

In [94]:
ticker_symbol.info

{'address1': '1600 Amphitheatre Parkway',
 'city': 'Mountain View',
 'state': 'CA',
 'zip': '94043',
 'country': 'United States',
 'phone': '650-253-0000',
 'website': 'https://abc.xyz',
 'industry': 'Internet Content & Information',
 'industryKey': 'internet-content-information',
 'industryDisp': 'Internet Content & Information',
 'sector': 'Communication Services',
 'sectorKey': 'communication-services',
 'sectorDisp': 'Communication Services',
 'longBusinessSummary': 'Alphabet Inc. offers various products and platforms in the United States, Europe, the Middle East, Africa, the Asia-Pacific, Canada, and Latin America. It operates through Google Services, Google Cloud, and Other Bets segments. The Google Services segment provides products and services, including ads, Android, Chrome, devices, Gmail, Google Drive, Google Maps, Google Photos, Google Play, Search, and YouTube. It is also involved in the sale of apps and in-app purchases and digital content in the Google Play and YouTube; and devices, as well as in the provision of YouTube consumer subscription services. The Google Cloud segment offers AI infrastructure, Vertex AI platform, cybersecurity, data and analytics, and other services; Google Workspace that include cloud-based communication and collaboration tools for enterprises, such as Calendar, Gmail, Docs, Drive, and Meet; and other services for enterprise customers. The Other Bets segment sells healthcare-related and internet services. The company was incorporated in 1998 and is headquartered in Mountain View, California.',
 'fullTimeEmployees': 190167,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Sundar  Pichai',
   'age': 51,
   'title': 'CEO & Director',
   'yearBorn': 1973,
   'fiscalYear': 2024,
   'totalPay': 10319413,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Ruth M. Porat',
   'age': 66,
   'title': 'President & Chief Investment Officer',
   'yearBorn': 1958,
   'fiscalYear': 2024,
   'totalPay': 3023363,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Dr. Lawrence Edward Page II',
   'age': 51,
   'title': 'Co-Founder & Director',
   'yearBorn': 1973,
   'fiscalYear': 2024,
   'totalPay': 1,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Sergey  Brin',
   'age': 50,
   'title': 'Co-Founder & Director',
   'yearBorn': 1974,
   'fiscalYear': 2024,
   'totalPay': 1,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Anat  Ashkenazi',
   'age': 51,
   'title': 'Senior VP & CFO',
   'yearBorn': 1973,
   'fiscalYear': 2024,
   'totalPay': 11455556,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. J. Kent Walker',
   'age': 63,
   'title': 'President of Global Affairs, Chief Legal Officer & Company Secretary',
   'yearBorn': 1961,
   'fiscalYear': 2024,
   'totalPay': 3019696,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Philipp  Schindler',
   'age': 53,
   'title': 'Senior Vice President & Chief Business Officer of Google',
   'yearBorn': 1971,
   'fiscalYear': 2024,
   'totalPay': 3051699,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Amie Thuener O'Toole",
   'age': 49,
   'title': 'Corporate Controller, Chief Accounting Officer & VP',
   'yearBorn': 1975,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Ellen  West',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Fiona Clare Cicconi',
   'age': 58,
   'title': 'Chief People Officer',
   'yearBorn': 1966,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 7,
 'boardRisk': 9,
 'compensationRisk': 10,
 'shareHolderRightsRisk': 10,
 'overallRisk': 10,
 'governanceEpochDate': 1761955200,
 'compensationAsOfEpochDate': 1735603200,
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 281.48,
 'open': 282.79,
 'dayLow': 277.03,
 'dayHigh': 286.0,
 'regularMarketPreviousClose': 281.48,
 'regularMarketOpen': 282.79,
 'regularMarketDayLow': 277.03,
 'regularMarketDayHigh': 286.0,
 'dividendRate': 0.84,
 'dividendYield': 0.3,
 'exDividendDate': 1757289600,
 'payoutRatio': 0.0809,
 'beta': 1.0,
 'trailingPE': 27.785574,
 'forwardPE': 31.382812,
 'volume': 39267945,
 'regularMarketVolume': 39267945,
 'averageVolume': 33464900,
 'averageVolume10days': 37591970,
 'averageDailyVolume10Day': 37591970,
 'bid': 280.76,
 'ask': 281.46,
 'bidSize': 5,
 'askSize': 5,
 'marketCap': 3396526145536,
 'fiftyTwoWeekLow': 140.53,
 'fiftyTwoWeekHigh': 291.59,
 'allTimeHigh': 291.59,
 'allTimeLow': 2.401401,
 'priceToSalesTrailing12Months': 8.811252,
 'fiftyDayAverage': 243.857,
 'twoHundredDayAverage': 192.73006,
 'trailingAnnualDividendRate': 1.02,
 'trailingAnnualDividendYield': 0.003623703,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 3338818813952,
 'profitMargins': 0.32233003,
 'floatShares': 10814324730,
 'sharesOutstanding': 5818000000,
 'sharesShort': 58341664,
 'sharesShortPriorMonth': 67329048,
 'sharesShortPreviousMonthDate': 1757894400,
 'dateShortInterest': 1760486400,
 'sharesPercentSharesOut': 0.0047999998,
 'heldPercentInsiders': 0.0026,
 'heldPercentInstitutions': 0.80801004,
 'shortRatio': 1.88,
 'shortPercentOfFloat': 0.01,
 'impliedSharesOutstanding': 12079114264,
 'bookValue': 32.033,
 'priceToBook': 8.778135,
 'lastFiscalYearEnd': 1735603200,
 'nextFiscalYearEnd': 1767139200,
 'mostRecentQuarter': 1759190400,
 'earningsQuarterlyGrowth': 0.33,
 'netIncomeToCommon': 124250996736,
 'trailingEps': 10.12,
 'forwardEps': 8.96,
 'lastSplitFactor': '20:1',
 'lastSplitDate': 1658102400,
 'enterpriseToRevenue': 8.662,
 'enterpriseToEbitda': 22.999,
 '52WeekChange': 0.6614866,
 'SandP52WeekChange': 0.19736934,
 'lastDividendValue': 0.21,
 'lastDividendDate': 1757289600,
 'quoteType': 'EQUITY',
 'currentPrice': 281.19,
 'targetHighPrice': 350.0,
 'targetLowPrice': 185.0,
 'targetMeanPrice': 307.07245,
 'targetMedianPrice': 325.0,
 'recommendationMean': 1.48485,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 53,
 'totalCash': 98496004096,
 'totalCashPerShare': 8.162,
 'ebitda': 145174003712,
 'totalDebt': 44195000320,
 'quickRatio': 1.563,
 'currentRatio': 1.747,
 'totalRevenue': 385476001792,
 'debtToEquity': 11.424,
 'revenuePerShare': 31.714,
 'returnOnAssets': 0.16275999,
 'returnOnEquity': 0.3545,
 'grossProfits': 228095000576,
 'freeCashflow': 47997751296,
 'operatingCashflow': 151424008192,
 'earningsGrowth': 0.353,
 'revenueGrowth': 0.159,
 'grossMargins': 0.59172,
 'ebitdaMargins': 0.37660998,
 'operatingMargins': 0.30512,
 'financialCurrency': 'USD',
 'symbol': 'GOOGL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 1092922200000,
 'postMarketChangePercent': -0.10355942,
 'postMarketPrice': 280.8988,
 'postMarketChange': -0.29119873,
 'regularMarketChange': -0.29000854,
 'regularMarketDayRange': '277.03 - 286.0',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 33464900,
 'fiftyTwoWeekLowChange': 140.66,
 'fiftyTwoWeekLowChangePercent': 1.0009251,
 'fiftyTwoWeekRange': '140.53 - 291.59',
 'fiftyTwoWeekHighChange': -10.399994,
 'fiftyTwoWeekHighChangePercent': -0.0356665,
 'fiftyTwoWeekChangePercent': 66.14867,
 'dividendDate': 1757894400,
 'earningsTimestamp': 1761768000,
 'earningsTimestampStart': 1761768000,
 'earningsTimestampEnd': 1761768000,
 'earningsCallTimestampStart': 1761773400,
 'earningsCallTimestampEnd': 1761773400,
 'isEarningsDateEstimate': False,
 'epsTrailingTwelveMonths': 10.12,
 'epsForward': 8.96,
 'epsCurrentYear': 10.4851,
 'priceEpsCurrentYear': 26.818056,
 'corporateActions': [],
 'postMarketTime': 1761955191,
 'regularMarketTime': 1761940802,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_29096',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EST',
 'gmtOffSetMilliseconds': -18000000,
 'market': 'us_market',
 'esgPopulated': False,
 'regularMarketChangePercent': -0.10302989,
 'regularMarketPrice': 281.19,
 'marketState': 'PREPRE',
 'longName': 'Alphabet Inc.',
 'fiftyDayAverageChange': 37.333008,
 'fiftyDayAverageChangePercent': 0.15309386,
 'twoHundredDayAverageChange': 88.459946,
 'twoHundredDayAverageChangePercent': 0.45898366,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '1.5 - Strong Buy',
 'cryptoTradeable': False,
 'shortName': 'Alphabet Inc.',
 'trailingPegRatio': 1.6714}

In [95]:
# the ownership composition
ticker_symbol.major_holders

Breakdown                          Value
insidersPercentHeld              0.00260
institutionsPercentHeld          0.80801
institutionsFloatPercentHeld     0.81012
institutionsCount             6457.00000

In [96]:
ticker_symbol.institutional_holders

,Date Reported,Holder,pctHeld,Shares,Value,pctChange
0,2025-06-30,Vanguard Group Inc,0.0888,516559609,145251397715,0.01320
1,2025-06-30,Blackrock Inc.,0.0740,430223692,120974601003,-0.02130
2,2025-06-30,State Street Corporation,0.0395,229954269,64660841461,0.01770
3,2025-06-30,"FMR, LLC",0.0372,216384449,60845143742,-0.02160
4,2025-06-30,"Geode Capital Management, LLC",0.0243,141615284,39820802053,0.03070
5,2025-06-30,Morgan Stanley,0.0231,134489927,37817222901,0.05660
6,2025-06-30,NORGES BANK,0.0214,124520276,35013856712,-0.03330
7,2025-06-30,Laurel Wealth Advisors LLC,0.0149,86507000,24324903541,1007.21655
8,2025-06-30,Price (T.Rowe) Associates Inc,0.0128,74223815,20870994721,-0.16730
9,2025-06-30,Bank of America Corporation,0.0121,70489308,19820888688,-0.01050

In [97]:
ticker_symbol.actions

                           Dividends  Stock Splits
Date
2014-04-03 00:00:00-04:00       0.00         1.998
2022-07-18 00:00:00-04:00       0.00        20.000
2024-06-10 00:00:00-04:00       0.20         0.000
2024-09-09 00:00:00-04:00       0.20         0.000
2024-12-09 00:00:00-05:00       0.20         0.000
2025-03-10 00:00:00-04:00       0.20         0.000
2025-06-09 00:00:00-04:00       0.21         0.000
2025-09-08 00:00:00-04:00       0.21         0.000

In [98]:
ticker_symbol.dividends

Date
2024-06-10 00:00:00-04:00    0.20
2024-09-09 00:00:00-04:00    0.20
2024-12-09 00:00:00-05:00    0.20
2025-03-10 00:00:00-04:00    0.20
2025-06-09 00:00:00-04:00    0.21
2025-09-08 00:00:00-04:00    0.21
Name: Dividends, dtype: float64

Fiancial statements: 
- Income Statement
- Balance Sheet

In [99]:
ticker_symbol.financials # Income Statement

,2024-12-31,2023-12-31,2022-12-31,2021-12-31
Tax Effect Of Unusual Items,3.401360e+08,-3.737710e+08,-1.035090e+09,2.002968e+09
Tax Rate For Calcs,1.640000e-01,1.390000e-01,1.590000e-01,1.620000e-01
Normalized EBITDA,1.333200e+11,1.006600e+11,9.167000e+10,9.115700e+10
Total Unusual Items,2.074000e+09,-2.689000e+09,-6.510000e+09,1.236400e+10
Total Unusual Items Excluding Goodwill,2.074000e+09,-2.689000e+09,-6.510000e+09,1.236400e+10
Net Income From Continuing Operation Net Minority Interest,1.001180e+11,7.379500e+10,5.997200e+10,7.603300e+10
Reconciled Depreciation,1.531100e+10,1.194600e+10,1.347500e+10,1.244100e+10
Reconciled Cost Of Revenue,1.463060e+11,1.333320e+11,1.262030e+11,1.109390e+11
EBITDA,1.353940e+11,9.797100e+10,8.516000e+10,1.035210e+11
EBIT,1.200830e+11,8.602500e+10,7.168500e+10,9.108000e+10
Net Interest Income,4.214000e+09,3.557000e+09,1.817000e+09,1.153000e+09
Interest Expense,2.680000e+08,3.080000e+08,3.570000e+08,3.460000e+08
Interest Income,4.482000e+09,3.865000e+09,2.174000e+09,1.499000e+09
Normalized Income,9.838414e+10,7.611023e+10,6.544691e+10,6.567197e+10
Net Income From Continuing And Discontinued Operation,1.001180e+11,7.379500e+10,5.997200e+10,7.603300e+10
Total Expenses,2.376280e+11,2.231010e+11,2.079940e+11,1.789230e+11
Total Operating Income As Reported,1.123900e+11,8.429300e+10,7.484200e+10,7.871400e+10
Diluted Average Shares,1.244700e+10,1.272200e+10,1.315900e+10,1.355348e+10
Basic Average Shares,1.231900e+10,1.263000e+10,1.306300e+10,1.335300e+10
Diluted EPS,8.040000e+00,5.800000e+00,4.560000e+00,5.610000e+00
Basic EPS,8.130000e+00,5.840000e+00,4.590000e+00,5.694000e+00
Diluted NI Availto Com Stockholders,1.001180e+11,7.379500e+10,5.997200e+10,7.603300e+10
Net Income Common Stockholders,1.001180e+11,7.379500e+10,5.997200e+10,7.603300e+10
Net Income,1.001180e+11,7.379500e+10,5.997200e+10,7.603300e+10
Net Income Including Noncontrolling Interests,1.001180e+11,7.379500e+10,5.997200e+10,7.603300e+10
Net Income Continuous Operations,1.001180e+11,7.379500e+10,5.997200e+10,7.603300e+10
Tax Provision,1.969700e+10,1.192200e+10,1.135600e+10,1.470100e+10
Pretax Income,1.198150e+11,8.571700e+10,7.132800e+10,9.073400e+10
Other Income Expense,3.211000e+09,-2.133000e+09,-5.331000e+09,1.086700e+10
Other Non Operating Income Expenses,1.137000e+09,5.560000e+08,1.179000e+09,-1.497000e+09
Special Income Charges,-1.880000e+08,-6.280000e+08,-3.370000e+08,3.340000e+08
Write Off,1.880000e+08,6.280000e+08,3.370000e+08,-3.340000e+08
Earnings From Equity Interest,-1.880000e+08,-6.280000e+08,-3.370000e+08,3.340000e+08
Gain On Sale Of Security,2.262000e+09,-2.061000e+09,-6.173000e+09,1.203000e+10
Net Non Operating Interest Income Expense,4.214000e+09,3.557000e+09,1.817000e+09,1.153000e+09
Interest Expense Non Operating,2.680000e+08,3.080000e+08,3.570000e+08,3.460000e+08
Interest Income Non Operating,4.482000e+09,3.865000e+09,2.174000e+09,1.499000e+09
Operating Income,1.123900e+11,8.429300e+10,7.484200e+10,7.871400e+10
Operating Expense,9.132200e+10,8.976900e+10,8.179100e+10,6.798400e+10
Research And Development,4.932600e+10,4.542700e+10,3.950000e+10,3.156200e+10
Selling General And Administration,4.199600e+10,4.434200e+10,4.229100e+10,3.642200e+10
Selling And Marketing Expense,2.780800e+10,2.791700e+10,2.656700e+10,2.291200e+10
General And Administrative Expense,1.418800e+10,1.642500e+10,1.572400e+10,1.351000e+10
Other Gand A,1.418800e+10,1.642500e+10,1.572400e+10,1.351000e+10
Gross Profit,2.037120e+11,1.740620e+11,1.566330e+11,1.466980e+11
Cost Of Revenue,1.463060e+11,1.333320e+11,1.262030e+11,1.109390e+11
Total Revenue,3.500180e+11,3.073940e+11,2.828360e+11,2.576370e+11
Operating Revenue,3.500180e+11,3.073940e+11,2.828360e+11,2.576370e+11

In [100]:
ticker_symbol.balance_sheet # Balance Sheet
# show all rows
pd.set_option('display.max_rows', None)
ticker_symbol.balance_sheet

,2024-12-31,2023-12-31,2022-12-31,2021-12-31,2020-12-31
Treasury Shares Number,NaN,0.000000e+00,NaN,NaN,NaN
Ordinary Shares Number,1.221100e+10,1.246000e+10,1.284900e+10,1.324242e+10,NaN
Share Issued,1.221100e+10,1.246000e+10,1.284900e+10,1.324242e+10,NaN
Total Debt,2.546100e+10,2.712100e+10,2.967900e+10,2.839500e+10,NaN
Tangible Book Value,2.931990e+11,2.541810e+11,2.271840e+11,2.272620e+11,NaN
Invested Capital,3.359670e+11,2.952490e+11,2.690010e+11,2.644790e+11,NaN
Working Capital,7.458900e+10,8.971600e+10,9.549500e+10,1.238890e+11,NaN
Net Tangible Assets,2.931990e+11,2.541810e+11,2.271840e+11,2.272620e+11,NaN
Capital Lease Obligations,1.457800e+10,1.525100e+10,1.682200e+10,1.555100e+10,NaN
Common Stock Equity,3.250840e+11,2.833790e+11,2.561440e+11,2.516350e+11,NaN
Total Capitalization,3.359670e+11,2.952490e+11,2.690010e+11,2.644790e+11,NaN
Total Equity Gross Minority Interest,3.250840e+11,2.833790e+11,2.561440e+11,2.516350e+11,NaN
Stockholders Equity,3.250840e+11,2.833790e+11,2.561440e+11,2.516350e+11,NaN
Gains Losses Not Affecting Retained Earnings,-4.800000e+09,-4.402000e+09,-7.603000e+09,-1.623000e+09,NaN
Other Equity Adjustments,-4.800000e+09,-4.402000e+09,-7.603000e+09,-1.623000e+09,NaN
Retained Earnings,2.450840e+11,2.112470e+11,1.955630e+11,1.914840e+11,NaN
Capital Stock,8.480000e+10,7.653400e+10,6.818400e+10,6.177400e+10,NaN
Common Stock,8.480000e+10,7.653400e+10,6.818400e+10,6.177400e+10,NaN
Preferred Stock,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
Total Liabilities Net Minority Interest,1.251720e+11,1.190130e+11,1.091200e+11,1.076330e+11,NaN
Total Non Current Liabilities Net Minority Interest,3.605000e+10,3.719900e+10,3.982000e+10,4.337900e+10,NaN
Other Non Current Liabilities,4.694000e+09,4.395000e+09,2.247000e+09,2.205000e+09,NaN
Tradeand Other Payables Non Current,8.782000e+09,8.474000e+09,9.258000e+09,9.176000e+09,NaN
Non Current Deferred Liabilities,NaN,1.396000e+09,1.113000e+09,5.792000e+09,4.042000e+09
Non Current Deferred Revenue,NaN,9.110000e+08,5.990000e+08,5.350000e+08,4.810000e+08
Non Current Deferred Taxes Liabilities,NaN,4.850000e+08,5.140000e+08,5.257000e+09,3.561000e+09
Long Term Debt And Capital Lease Obligation,2.257400e+10,2.433000e+10,2.720200e+10,2.620600e+10,NaN
Long Term Capital Lease Obligation,1.169100e+10,1.246000e+10,1.434500e+10,1.336200e+10,NaN
Long Term Debt,1.088300e+10,1.187000e+10,1.285700e+10,1.284400e+10,NaN
Current Liabilities,8.912200e+10,8.181400e+10,6.930000e+10,6.425400e+10,NaN
Other Current Liabilities,6.322000e+09,9.525000e+09,9.106000e+09,9.799000e+09,NaN
Current Deferred Liabilities,5.036000e+09,4.137000e+09,3.908000e+09,3.288000e+09,NaN
Current Deferred Revenue,5.036000e+09,4.137000e+09,3.908000e+09,3.288000e+09,NaN
Current Debt And Capital Lease Obligation,2.887000e+09,2.791000e+09,2.477000e+09,2.189000e+09,NaN
Current Capital Lease Obligation,2.887000e+09,2.791000e+09,2.477000e+09,2.189000e+09,NaN
Pensionand Other Post Retirement Benefit Plans Current,1.506900e+10,1.514000e+10,1.402800e+10,1.388900e+10,NaN
Payables And Accrued Expenses,5.980800e+10,5.022100e+10,3.978100e+10,3.508900e+10,NaN
Current Accrued Expenses,4.891600e+10,3.998000e+10,3.302100e+10,2.905200e+10,NaN
Payables,1.089200e+10,1.024100e+10,6.760000e+09,6.037000e+09,NaN
Other Payable,NaN,NaN,NaN,3.970000e+08,7.540000e+08
Total Tax Payable,2.905000e+09,2.748000e+09,1.632000e+09,8.080000e+08,NaN
Income Tax Payable,2.905000e+09,2.748000e+09,1.632000e+09,8.080000e+08,NaN
Accounts Payable,7.987000e+09,7.493000e+09,5.128000e+09,6.037000e+09,NaN
Total Assets,4.502560e+11,4.023920e+11,3.652640e+11,3.592680e+11,NaN
Total Non Current Assets,2.865450e+11,2.308620e+11,2.004690e+11,1.711250e+11,NaN
Other Non Current Assets,1.487400e+10,1.005100e+10,8.707000e+09,5.361000e+09,NaN
Non Current Deferred Assets,1.718000e+10,1.216900e+10,5.261000e+09,1.284000e+09,NaN
Non Current Deferred Taxes Assets,1.718000e+10,1.216900e+10,5.261000e+09,1.284000e+09,NaN
Investments And Advances,3.798200e+10,3.100800e+10,3.049200e+10,2.954900e+10,NaN
Investmentin Financial Assets,3.798200e+10,3.100800e+10,3.049200e+10,2.954900e+10,NaN
Available For Sale Securities,3.798200e+10,3.100800e+10,3.049200e+10,2.954900e+10,NaN
Goodwill And Other Intangible Assets,3.188500e+10,2.919800e+10,2.896000e+10,2.437300e+10,NaN
Other Intangible Assets,NaN,NaN,2.084000e+09,1.417000e+09,1.445000e+09
Goodwill,3.188500e+10,2.919800e+10,2.896000e+10,2.295600e+10,NaN
Net PPE,1.846240e+11,1.484360e+11,1.270490e+11,1.105580e+11,NaN
Accumulated Depreciation,-7.939000e+10,-6.745800e+10,-5.904200e+10,-4.941400e+10,NaN
Gross PPE,2.640140e+11,2.158940e+11,1.860910e+11,1.599720e+11,NaN
Leases,NaN,1.142500e+10,1.057500e+10,9.146000e+09,7.516000e+09
Construction In Progress,NaN,3.522900e+10,2.765700e+10,2.317200e+10,2.311100e+10
Other Properties,2.203000e+11,1.754590e+11,8.064800e+10,6.856500e+10,NaN
Machinery Furniture Equipment,NaN,4.720000e+08,3.140000e+08,2.080000e+08,1.970000e+08
Buildings And Improvements,4.371400e+10,4.043500e+10,NaN,NaN,NaN
Land And Improvements,NaN,7.408300e+10,6.689700e+10,5.888100e+10,4.973200e+10
Properties,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
Current Assets,1.637110e+11,1.715300e+11,1.647950e+11,1.881430e+11,NaN
Other Current Assets,1.571400e+10,1.265000e+10,1.077500e+10,8.020000e+09,NaN
Inventory,NaN,NaN,2.670000e+09,1.170000e+09,7.280000e+08
Receivables,5.234000e+10,4.796400e+10,4.025800e+10,3.930400e+10,NaN
Taxes Receivable,NaN,NaN,NaN,9.660000e+08,4.540000e+08
Accounts Receivable,5.234000e+10,4.796400e+10,4.025800e+10,3.930400e+10,NaN
Allowance For Doubtful Accounts Receivable,-8.790000e+08,-7.710000e+08,-7.540000e+08,-5.500000e+08,NaN
Gross Accounts Receivable,5.321900e+10,4.873500e+10,4.101200e+10,3.985400e+10,NaN
Cash Cash Equivalents And Short Term Investments,9.565700e+10,1.109160e+11,1.137620e+11,1.396490e+11,NaN
Other Short Term Investments,7.219100e+10,8.686800e+10,9.188300e+10,1.187040e+11,NaN
Cash And Cash Equivalents,2.346600e+10,2.404800e+10,2.187900e+10,2.094500e+10,NaN

In [105]:
# ! pip install openpyxl

In [106]:
# export balance sheet to excel with ticker symbol name
ticker_symbol.balance_sheet.to_excel('{}_balance_sheet.xlsx'.format(ticker_symbol.ticker))
print('Exported balance sheet to {}_balance_sheet.xlsx'.format(ticker_symbol.ticker))

Exported balance sheet to GOOGL_balance_sheet.xlsx

END